### PR TITLE
Images in redistricting program Issue #104

### PR DESCRIPTION
**Pull request by am10nxw**
Created new NewFigure files with red and blue shaded differently so you could see the shade differences when printing on a monochromatic printer. Updated the NewRedistring.md file to point to the new image files.
PXL_20211116_191100778

### CODE REVIEW

**Comment by MXHJohn314** [comment]
All version1 pictures have much more distinct shades of grey than their previous versions. The only thing that concerns me is the redundancy of having the old pictures. I think the old pictures should be removed, and the new images should have the `1` removed from their names, directly replacing the old files. Is there any good reason to keep the old versions?

**Comment by am10nxw** [comment]
I just have a habit of keeping everything. If you want me to remove the old versions and use the same name I'm happy to make the changes.

**Comment by jody** [comment]
> Is there any good reason to keep the old versions?

Not in this instance. I support using the version control process to update the image files rather than adding new files.

As a counter-example, the image changes made previously **did** warrant keeping the originals because there were **significant** changes that potentially **conveyed meaning** and there was known to be **insufficient review** prior to merging the changes. Thus we wanted the ability to easily look at both versions simultaneously.

**Review by jody — CHANGES_REQUESTED** [review]
New images work to address the concerns in issue #104.

**Update the image files currently used** in [RedistrictingProgram.md](https://github.com/MetroCS/redistricting/blob/master/RedistrictingProgram.md) rather than adding new files.

- `RedistrictingProgram.md` itself should **not** be modified.
- Files with new _names_ should **not** be created in the repository.

**Review by jody — CHANGES_REQUESTED** [review]
If only the images have changed, why is there a change to **NewRedistricting.md**?

**Comment by am10nxw** [comment]
When I view NewRedistricting.md locally on my machine the document doesn't find NewfigureA.png or NewfigureB.png. It does find NewfigureC.png, and NewfigureD.png. I figured out it was because there was a / in front of the link to the image on A and B. so I removed the / to view the document. 

I realize that is not something this issue is supposed to address, so I removed making that change in this pull request.

**Comment by jody** [comment]
> When I view NewRedistricting.md locally on my machine the document doesn't find NewfigureA.png or NewfigureB.png. It does find NewfigureC.png, and NewfigureD.png. I figured out it was because there was a / in front of the link to the image on A and B. so I removed the / to view the document.

Just need to track the changes.  Please file a new issue (bug) for this, indicating how to replicate the error. Thank you!

**Review by jody — APPROVED** [review]

**Pull request merged**
