### PR TITLE
Wrote 2 more tests for the region class

### PR DESCRIPTION
**Pull request by flip1012**
Wrote two tests for Region constructor: public Region(Set<Location>, Set<Voter>) issue.

### CODE REVIEW

**Review by jody — CHANGES_REQUESTED** [review]
(1) This PR isn't linked to any active issue.  Please add a comment identifying the issue this addresses.
(2) This PR isn't up to date with the current MetroCS repository, please rebase to the current state of the repo.
(3) Unless the issue this is addressing requires modifications to other files, there should be no changes to a file other than RegionTest.java.
(4) 39 commits is a bit much for maintainers to weed through to determine appropriate commit message(s).  Please squash to those only commits that benefit from commenting and/or may need to be reversible.

**Review by Esmael377 — APPROVED** [review]

**Comment by Esmael377** [comment]
I agree this code. I did try to pushed to the DreamworkTechnologies : master

**Review by Esmael377 — APPROVED** [review]

**Comment by Esmael377** [comment]
It is passed all the requirements ( all Checks have passed). I did approved it too

**Comment by Esmael377** [comment]
The branch has no conflicts

**Comment by jody** [comment]
Unassociated with any identified issue.  Set to DRAFT status.

**Review by Esmael377 — APPROVED** [review]

**Comment by flip1012** [comment]
Closing this pull request. Old pull request no longer needed.

**Pull request closed without merging**
