### PR TITLE
Add Vision.md 

### PR DESCRIPTION
**Pull request by zmorlan1**
* Add Vision.md

* Update Vision.md

### CODE REVIEW

**Comment by mykewlker** [comment]
This documents adds a vision statement and list of stakeholders as needed by several user stories

**Comment by jody** [comment]
Intended to partially address User Story #1

**Comment by mykewlker** [comment]
Changes made on vocabulary, readme updated to point to vision statement

**Comment by jody** [comment]
What is the associated User Story?  This may be an ill-conceived PR.

No rationale provided for why the majority of content of the README file was removed.

No explanation of the reason existing wording was changed between in the proposed version of the README (e.g., the title and the objective).

There is a separate pull request (PR #17) that also includes addition of Vision.md.

Will not attempt to merge either PR until you have resolved what user stories each addresses and limit the PR contents to the appropriate user story.

"OLDREADME" is not a meaningful name.  (It further suggests that the information contained is no longer relevant.)

**Pull request closed without merging**
