### PR TITLE
Added StarGeneratorTest class. 

### PR DESCRIPTION
**Pull request by 13Lena**
Created an incomplete test class as a starting place, testing the following things:- The number of `Location` objects in each pattern is equivalent to some desired input `n`

- Each pattern is contiguous
- Each Location is unique within a particular patternWe suggest breaking up `generatePatternTest` method into private methods that test each of the above assertions individually. 

Even though the basics of the tests are here, it possible more components for the test class are needed.

### CODE REVIEW

**Review by MXHJohn314 — APPROVED** [review]
`voterRegionInputConstructorTest` is in good and working condition on my side. Approved.

**Review by jody — CHANGES_REQUESTED** [review]
This PR shows the number of files changed as 56. Because that can't be appropriate for the issue being addressed, I haven't done any review of specifics.

**Comment by MXHJohn314** [comment]
the number of files that have changed is due to the fact that many files
were reverted to their original files. The team had to revert those files
due to essentially scrapping previous work.

**Comment by jody** [comment]
I need help to understand why there wouldn't be exactly 1 file added and no other files changed.
See: https://github.com/MetroCS/redistricting/pull/140/files

**Comment by jody** [comment]
Appears to be a duplicate of #157

**Pull request closed without merging**
