### PR TITLE
Created new unit test for RegionTest to address Issue #119

### PR DESCRIPTION
**Pull request by bishnu19**
We created a test to test the one-parameter constructor for the Region object. The test checked the region size, the number of voters, and the location of those voters. All of the tests were passed.

### CODE REVIEW

**Comment by bderosie** [comment]
Link for Issue #119

**Review by jody — CHANGES_REQUESTED** [review]
This branch has conflicts.
It also results in error notifications from Checkstyle.

**Comment by bishnu19** [comment]
created PR fixing checkstyle errors.

**Comment by jody** [comment]
No explanation why this was reopened. Conflicts with repository.

**Comment by bishnu19** [comment]
> No explanation why this was reopened. Conflicts with repository.

I apologize for that. We thought it is better to work on this PR because after solving conflicts we got more issues on the previous PR.

**Pull request closed without merging**
