### PR TITLE
Changes to RedistrictingDriver

### PR DESCRIPTION
**Pull request by Devin-S-9801**
Team: The Collective

Because of the confusion surrounding the name RedistrictingDriver we have decided to rename it to RedistrictingDemo and created a folder named Demo to contain the java file and help to identify it as a demo. We have also changed some of the comments to help specify the purpose of the code.

### CODE REVIEW

**Comment by jody** [comment]
Please associate this PR with an open issue in the project.

**Comment by jody** [comment]
Removing RedistrictingDriver from the package is becoming a highly likely outcome. All issues/PRs that address concerns involving RedistrictingDriver are thus likely to be irrelevant. Am putting all such activity "on hold" for now.

**Comment by Devin-S-9801** [comment]
My apologies this was submitted in response to issue #90.

**Comment by jody** [comment]
See new issue #145

**Pull request closed without merging**
