### PR TITLE
Added Documentation for Running demo - issue #9

### PR DESCRIPTION
**Pull request by thrandale**
Provides a solution for https://github.com/MetroCS/redistricting/issues/9

### CODE REVIEW

**Comment by jody** [comment]
Either one of the following two instruction types seem more appropriate.
* Provide instructions for building and running the jar without installing Ant.
  * This might make sense for _user_ and _educator_ stakeholder types.
  * In this case, the instructions may be long enough to warrant a separate file.
* Refer to the Ant "run" target.
  * Replicating the instructions provided inside `build.xml` adds redundancy, thereby increasing the potential for inconsistency in the future.
  * In this case, the instructions are likely to be one or two lines, which may be better as included in another document.

**Review by jody — CHANGES_REQUESTED** [review]
See preceding comment regarding alternative ways of presenting instruction.

**Comment by thrandale** [comment]
We have updated the Contributing.md to direct users to "ant run", and removed the Dedicated Documentation for running.

**Review by jody — COMMENTED** [review]
The original documentation, which is in the context of **contributing** to the project was appropriate as it stood.

I'm going to close this PR and recommend that the discussion be conducted back at the originating User Story (Issue #9).

**Pull request closed without merging**
